DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;
USE employee_db;

CREATE TABLE department (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE role (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(30) NOT NULL, 
    salary INT NOT NULL,
	department_id INT NOT NULL
);

CREATE TABLE employee (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	role_id INT NOT NULL,
    manager_id INT NOT NULL
);

SELECT * FROM department;
SELECT * FROM role;
SELECT * FROM employee;